version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "maven"
    directory: "/.github/extra-1"
    schedule:
      interval: "monthly"

  - package-ecosystem: "maven"
    directory: "/.github/extra-2"
    schedule:
      interval: "monthly"

  - package-ecosystem: "maven"
    directory: "/.github/extra-3"
    schedule:
      interval: "monthly"

  - package-ecosystem: "npm"
    directory: "/front-vue"
    schedule:
      interval: "daily"
